const localUrl = '/pages/memberModule/assets/images/'; // 本地地址
const cdnUrl = 'https://tc.woaap.com/aierjian-ecrm-weapp/memberModule/'; // cdn地址

export default {
  screen_banner: `${localUrl}screen_banner.jpg`,
  screen_logo: `${localUrl}screen_logo.png`,
  screen_btn: `${localUrl}screen_btn.png`,
  register_logo: `${localUrl}register_logo.jpg`,
  index_banner: `${cdnUrl}index_banner.jpg`,
  index_banner_share: `${cdnUrl}index_banner_share.jpg`,
  index_logo: `${localUrl}index_logo.png`,
  icon_edit: `${localUrl}icon_edit.png`,
  icon_index1: `${localUrl}icon_index1.png`,
  icon_index2: `${localUrl}icon_index2.png`,
  icon_index3: `${localUrl}icon_index3.png`,
  icon_index4: `${localUrl}icon_index4.png`,
  icon_index5: `${localUrl}icon_index5.png`,
  icon_index6: `${localUrl}icon_index6.png`,
  icon_contact: `${localUrl}icon_contact.png`,
  icon_qr: `${localUrl}icon_qr.png`,
  card_bg: `${cdnUrl}card_bg.png`,
  icon_store_tel: `${localUrl}icon_store_tel.png`,
  icon_store_tel_gray: `${localUrl}icon_store_tel_gray.png`,
  icon_store_gps: `${localUrl}icon_store_gps.png`,
  index_banner_share2: `${cdnUrl}index_banner_share2.jpg`,
  share_white_bg: `${localUrl}share_white_bg.png`,
  icon_ask: `${localUrl}icon_ask.png`,
  icon_noPart: `${localUrl}icon_noPart.png`,
  icon_prize_bg: `${localUrl}icon_prize_bg.png`,
  icon_prize_dis_bg: `${localUrl}icon_prize_dis_bg.png`,
  icon_right1: `${localUrl}icon_right1.png`,
  icon_right2: `${localUrl}icon_right2.png`,
  icon_right3: `${localUrl}icon_right3.png`,
  icon_right4: `${localUrl}icon_right4.png`,
  icon_right5: `${localUrl}icon_right5.png`,
  icon_logo_bg: `${localUrl}icon_logo_bg.png`,
  qustion_bg: `${localUrl}qustion_bg.jpg`,
  qustion_bg_big: `${localUrl}qustion_bg_big.jpg`,
  prize_coating: `${cdnUrl}prize_coating.png`,
  prize_no: `${cdnUrl}prize_no.png`,
  icon_close: `${localUrl}icon_close.png`,
}
