const localUrl = '/pages/memberModule/assets/images/'; // 本地地址
const cdnUrl = 'https://tc.woaap.com/aierjian-ecrm-weapp/memberModule/'; // cdn地址

export default {
  icon_build: `${localUrl}icon_build.png`,
  screen_banner_init: `${localUrl}screen_banner.jpg`,
  screen_banner_big: `${localUrl}screen_banner.jpg`,
  screen_logo: `${localUrl}screen_logo.png`,
  screen_btn: `${localUrl}screen_btn.png`,
  screen_decorate: `${localUrl}screen_decorate.png`,
  clause_privacy1: `${cdnUrl}clause_privacy1.jpg`,
  clause_privacy2: `${cdnUrl}clause_privacy2.jpg`,
  clause_privacy3: `${cdnUrl}clause_privacy3.jpg`,
  clause_privacy4: `${cdnUrl}clause_privacy4.jpg`,
  clause_use1: `${cdnUrl}clause_use1.jpg`,
  clause_use2: `${cdnUrl}clause_use2.jpg`,
  clause_use3: `${cdnUrl}clause_use3.jpg`,
  clause_use4: `${cdnUrl}clause_use4.jpg`,

  index_banner: `${localUrl}index_banner.jpg`,
  icon_order_gift: `${localUrl}icon_order_gift.png`,
  icon_order_cake: `${localUrl}icon_order_cake.png`,
  icon_order_reduce: `${localUrl}icon_order_reduce.png`,
  icon_notice: `${localUrl}icon_notice.png`,
  icon_search: `${localUrl}icon_search.png`,

  icon_edit: `${localUrl}icon_edit.png`,
  icon_contact: `${localUrl}icon_contact.png`,
  icon_qr: `${localUrl}icon_qr.png`,
  card_bg: `${cdnUrl}card_bg.png`,
  icon_store_tel: `${localUrl}icon_store_tel.png`,
  icon_store_tel_gray: `${localUrl}icon_store_tel_gray.png`,
  icon_store_gps: `${localUrl}icon_store_gps.png`,
  share_white_bg: `${localUrl}share_white_bg.png`,
  icon_ask: `${localUrl}icon_ask.png`,
  icon_noPart: `${localUrl}icon_noPart.png`,
  icon_prize_bg: `${localUrl}icon_prize_bg.png`,
  icon_prize_dis_bg: `${localUrl}icon_prize_dis_bg.png`,
  icon_logo_bg: `${localUrl}icon_logo_bg.png`,
  icon_logo_big: `${localUrl}icon_logo_big.png`,
  qustion_bg: `${cdnUrl}qustion_bg.jpg`,
  qustion_bg_big: `${cdnUrl}qustion_bg_big.jpg`,
  prize_coating: `${cdnUrl}prize_coating.jpg`,
  scratch_bg: `${cdnUrl}scratch_bg.png`,
  prize_no: `${cdnUrl}prize_no.png`,
  prize_white: `${cdnUrl}prize_white.png`,
  prize_bg_unused: `${localUrl}prize_bg_unused.png`,
  prize_bg_used: `${localUrl}prize_bg_used.png`,
  icon_prize_used_round_line: `${localUrl}icon_prize_used_round_line.png`,
  icon_no_prize: `${cdnUrl}icon_no_prize.png`,
  icon_close: `${localUrl}icon_close.png`,
  icon_close2: `${localUrl}icon_close2.png`,
  article1: `${cdnUrl}article1.jpg`,
  article2: `${cdnUrl}article2.jpg`,
  article3: `${cdnUrl}article3.jpg`,
  article4: `${cdnUrl}article4.jpg`,
  article5: `${cdnUrl}article5.jpg`,
  article6: `${cdnUrl}article6.jpg`,
  icon_add: `${localUrl}icon_add.png`,
  icon_prize_zero: `${localUrl}icon_prize_zero.png`,
}
